clusters = source, target

# Source cluster configuration
source.bootstrap.servers = kafka-0:9094,kafka-1:9095,kafka-2:9096
source.security.protocol = SASL_SSL
source.sasl.mechanism = PLAIN
source.sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
source.ssl.truststore.location = /kafka-creds/source/kafka.truststore.jks
source.ssl.truststore.password = password
source.ssl.endpoint.identification.algorithm =

# Target cluster configuration
target.bootstrap.servers = kafka-3:9094,kafka-4:9095,kafka-5:9096
target.security.protocol = SASL_SSL
target.sasl.mechanism = PLAIN
target.sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
target.ssl.truststore.location = /kafka-creds/target/kafka.truststore.jks
target.ssl.truststore.password = password
target.ssl.endpoint.identification.algorithm =

# Replication configuration
source->target.enabled = true
source->target.topics = .*
source->target.replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy
source->target.sync.group.offsets.enabled = false
source->target.emit.heartbeats.enabled = true
source->target.emit.heartbeats.interval.seconds = 5